version: '3.5'
services:
  namesrv:
    image: apache/rocketmq:latest
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    networks:
      - rocketmq_net

  broker:
    image: apache/rocketmq:latest
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqbroker -n namesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq_net

  console:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - namesrv
    networks:
      - rocketmq_net

networks:
  rocketmq_net:
    driver: bridge